name: Build master
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '30 04 * * *'

jobs:
  BuildMaster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Build and test
        run: |
          ./gradlew --no-daemon --stacktrace clean build test