name: Release PR
on:
  pull_request:
    types: [ labeled ]

jobs:
  ReleasePR:
    if: ${{ github.event.label.name == 'RELEASE' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Build and test
        run: |
          ./gradlew --no-daemon --stacktrace clean build test