name: Build PR
on: pull_request

jobs:
  BuildPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            --no-daemon
            --stacktrace
            clean
            build
            test
            currentVersion
      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            --no-daemon
            --stacktrace
            -PequinoRepository.username=${{ secrets.GITHUB_ACTOR }}
            -PequinoRepository.password=${{ secrets.GITHUB_TOKEN }}
            publish